import "bootstrap/dist/css/bootstrap.css";
import Nav from "../components/Nav/Nav";

export const metadata = {
  title: "PharmaZeal",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <Nav />
          {children}
        </div>
      </body>
    </html>
  );
}
