import "bootstrap/dist/css/bootstrap.css";
import Nav from "@/components/Nav/Nav";

import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";

export const metadata = {
  title: "PharmaZeal",
  description: "Generated by Next.js",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <div>
            <Nav />
            {children}
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
